FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    curl \
    vim \
    net-tools \
    iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

    WORKDIR /app

    